# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# SPDX-FileCopyrightText: Copyright 2022 Micron Technology, Inc.

name: Builds

on:
  push:
    branches:
      - master
      - "v[0-9]+.[0-9]+"
    paths-ignore:
      - "**.c"
      - "**.h"
      - "**.java"
      - "**/meson.build"
      - "subprojects/*.wrap"
      - "cross/*.ini"
      - .github/workflows/builds.yaml
      - meson_options.txt
      - pom.xml
      - VERSION
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**.c"
      - "**.h"
      - "**.java"
      - "**/meson.build"
      - "subprojects/*.wrap"
      - "cross/*.ini"
      - .github/workflows/builds.yaml
      - meson_options.txt
      - pom.xml
      - VERSION

concurrency:
  group: ${{ github.workflow }}-ignore-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  normal:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - almalinux-8
          - almalinux-9
          - cross-s390x
          - fedora-37
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
        buildtype: [release, debug]

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}/${{ matrix.image }}/${{ matrix.buildtype }}"
