name: checkoss

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout hse-java
        uses: actions/checkout@v3

      - name: checkoss
        run: |
          scripts/dev/checkoss.sh
