name: checkstyle

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.java"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout hse-java
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: checkstyle
        run: |
          mvn checkstyle:check
