# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# SPDX-FileCopyrightText: Copyright 2021 Micron Technology, Inc.

name: checkstyle

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.java"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout hse-java
        uses: actions/checkout@v3

      - name: Export Maven local repository
        id: maven-local-repository
        run: |
          local_repository=$(mvn help:evaluate -Dexpression=settings.localRepository --quiet -DforceStdout)
          echo "local-repository=$local_repository" >> "$GITHUB_OUTPUT"

      - name: Cache Maven dependencies
        id: maven-dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.maven-local-repository.outputs.local-repository }}
          key: maven-dependencies-${{ hashFiles('pom.xml') }}

      - name: checkstyle
        run: |
          mvn checkstyle:check
