# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# SPDX-FileCopyrightText: Copyright 2021 Micron Technology, Inc.

name: checkstyle

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**.java"

concurrency:
  group: ${{ github.workflow }}-ignore-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"
