name: checkstyle

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "**.java"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Skipping ${{ github.workflow }}/${{ github.job }}"
