name: checkstyle

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.java"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize
        run: |
          sudo apt-get install maven

      - uses: actions/checkout@v3

      - name: checkstyle
        run: |
          mvn checkstyle:check
