# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# SPDX-FileCopyrightText: Copyright 2022 Micron Technology, Inc.

name: ClangFormat

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.c"
      - "**.h"
      - .github/workflows/clang-format.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  determine-tag:
    runs-on: ubuntu-latest
    continue-on-error: false
    outputs:
      tag: ${{ steps.determine-tag.outputs.tag }}

    steps:
      - name: Determine tag
        id: determine-tag
        run: |
          if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
            echo "tag=$GITHUB_BASE_REF" >> "$GITHUB_OUTPUT"
          else
            echo "tag=$GITHUB_REF_NAME" >> "$GITHUB_OUTPUT"
          fi

  clang-format:
    runs-on: ubuntu-latest
    needs:
      - determine-tag
    container:
      image: ghcr.io/hse-project/ci-images/fedora-37:${{ needs.determine-tag.outputs.tag }}

    steps:
      - name: Checkout hse-java
        uses: actions/checkout@v3

      - name: Get clang-format
        run: |
          dnf install clang-tools-extra

      - name: Setup
        run: |
          meson setup builddir --fatal-meson-warnings --werror

      - name: Run clang-format
        run: |
          ninja -C builddir clang-format
